### ISSUE TITLE
re-post: in keypirinha naming question

### ISSUE THREAD

**Issue by itmestan** [TanninOne/keypirinha-allmygames#10]
hi! love the functionality of the plugin, thank you so much for putting it together.

one quick question. I'm wondering if there's a way we can chose to or opt out of the "AMG" naming scheme?

when searching for a game, I see "AMG Steam: Hades". seeing the AMG and platform ahead of the game breaks much of the continuity of keypirinha and can throw me off. while this is a nitpicky preference, is there a chance we can have this as an option in the configuration to simply opt out of "AMD [Platform]" when searching?

let me know please, thx!

**Comment by TanninOne** [comment]
1.6.0 allows you to disable both parts of the prefix individually. Let me know if there's any problems
