### ISSUE TITLE
Configuration options to disable parts of the plugin

### ISSUE THREAD

**Issue by ueffel** [TanninOne/keypirinha-allmygames#4]
It would be nice, if I could disable individual launchers via config.
Let's say I don't want the Windows Store part (because my package works better 😋) or I find that @EhsanKia's steam package works better or I just want to save some CPU cycles by disabling game launchers I haven't installed anyway.

I have something like this in mind:

```ini
[Steam]
#Default: yes
enable = no

[WinStore]
#Default: yes
enable = no

[Uplay]
#Default: yes
enable = no
...
```

or like this

```ini
[main]
steam_enabled = no
win_store_enabled = no
uplay_enabled = no
...
```

**Comment by on3nightstan** [comment]
seconding this! would love to configure this package to focus which launchers I want and don't want.
