### ISSUE TITLE
Can't read Steam manifest

### ISSUE THREAD

**Issue by on3nightstan** [TanninOne/keypirinha-allmygames#6]
tried installing this package for the first time on Steam's latest update since 7/28. the other Steam package was removed. 

>18:19:26.071 ** ERROR: allmygames.AllMyGames: [Steam] Failed to read manifest appmanifest_504370.acf vdf.parse: unexpected EOF (open key quote?) (appmanifest_504370.acf, line 1)
>18:19:26.071 allmygames.AllMyGames: failed to initialize repo Steam vdf.parse: unexpected EOF (open key quote?) (appmanifest_504370.acf, line 1)

I removed AMG and tried the other Steam package which worked fine. any suggestions?

**Comment by TanninOne** [comment]
I've seen steam store corrupted manifest files, my guess is that the mentioned file (the manifest for Battlerite) is indeed damaged.
The other steam package may ignore errors like this or log them and continue, which is what I will do in the next update.

Out of curiosity: Is Battlerite shown as installed in your steam? Does it work correctly?

**Comment by on3nightstan** [comment]
> Out of curiosity: Is Battlerite shown as installed in your steam? Does it work correctly?

it was, roughly a year ago. since it's no longer installed, what would you recommend? removing the manifest file?

**Comment by TanninOne** [comment]
@on3nightstan yeah, steam shouldn't have manifests for  uninstalled games
